### ISSUE TITLE
Attribute selector matching

### ISSUE THREAD

**Issue by robinlinden** [robinlinden/hastur#943]
https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

Needed for variable lookup on github.com as the color variables are set up like
```css
[data-color-mode="auto"][data-light-theme="light"] {
  --somevar: #123;
}
```
